spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://baiyao:3306/idm?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

server:
  # 单位 KB
  max-http-header-size: 100000
  port: 8081
  servlet:
    context-path: /idm
    # Session 过期时间，单位秒，小于60秒会取1分钟（设置3小时）
    session:
      timeout: 10800
logging:
  level:
    com.baiyao.identity.mapper: debug
nacos:
  # 配置中心
  config:
    server-addr: baiyao:8848
    namespace: 53f890e7-3291-46c4-93c9-df2c100c1c9c
    group: DEFAULT_GROUP
    auto-refresh: true
    data-ids: example,system-config.yaml
    username: nacos
    password: nacos
log:
  filePath: idm
